### ISSUE TITLE
Push & Edit Buttons are not Visible

### ISSUE THREAD

**Issue by Magedsaif** [husamahmud/LeetPush#29]
when i sunbmit a solution the Push and edit buttons are not visible to use 
![Screenshot from 2024-04-19 15-20-14](https://github.com/husamahmud/LeetPush/assets/111353344/b50a10a0-0bfe-48c9-a740-5e88b92e6bd8)

**Comment by TutTrue** [comment]
To reproduce the error:
1. Go to submissions page
2. Refresh the page
3. Submit the problem
